# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackSprint' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackSprint
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire', '~> 4.6'

  target 'HackSprintTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackSprintUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
